server:
  port: 8080

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    url: jdbc:mysql://47.114.142.39:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


exam:
  path: /root/springbootdemo/exam/exam_template.docx
#  path: D:\project\springboot-demo\src\test\java\com\gupao\springbootdemo\test\exam_template.docx